### ISSUE TITLE
Update node engines 

### ISSUE THREAD

**Issue by 2x5** [danneu/interval-cache#2]
Using yarn and Node 6.x to install this package requires you to use `--ignore-engines`, else you get:

`error interval-cache@0.0.1: The engine "node" is incompatible with this module. Expected version "5.x"`

Can we update package.json to include future versions, ie. `>=5.x`?

**Comment by danneu** [comment]
@shizazzle Sorry for the wait. I published your change as `0.0.2`.

Soon I'll release a `1.0.0` that incorporates my rewrite which addresses some issues like:

- Simpler implemenaion
- Failures are retried / improved error handling
- Explicitly use `cache.start()` to start the interval

The rewrite looks something like the `Cache` class in this file: https://github.com/danneu/guild/blob/master/server/cache2.js -- Sorry if you run into any of the issues that my rewrite fixes.
